apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service
          imagePullPolicy: Never
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DB_NAME
              value: "user_service"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: ""
            - name: EUREKA_HOST
              value: "service-registry"
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8082
      targetPort: 8082
